// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcModel.proto

package com.cczu.examples.hdfs.rpc.model;

public interface ShutdownResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cczu.examples.hdfs.rpc.ShutdownResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();
}
