// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcService.proto

package com.cczu.examples.hdfs.rpc.service;

import com.cczu.examples.hdfs.rpc.model.NameNodeModel;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030NameNodeRpcService.proto\022\032com.cczu.exa" +
      "mples.hdfs.rpc\032\026NameNodeRpcModel.proto2\235" +
      "\004\n\017NameNodeService\022e\n\010register\022+.com.ccz" +
      "u.examples.hdfs.rpc.RegisterRequest\032,.co" +
      "m.cczu.examples.hdfs.rpc.RegisterRespons" +
      "e\022h\n\theartbeat\022,.com.cczu.examples.hdfs." +
      "rpc.HeartbeatRequest\032-.com.cczu.examples" +
      ".hdfs.rpc.HeartbeatResponse\022\\\n\005mkdir\022(.c" +
      "om.cczu.examples.hdfs.rpc.MkdirRequest\032)" +
      ".com.cczu.examples.hdfs.rpc.MkdirRespons" +
      "e\022e\n\010shutdown\022+.com.cczu.examples.hdfs.r" +
      "pc.ShutdownRequest\032,.com.cczu.examples.h" +
      "dfs.rpc.ShutdownResponse\022t\n\rfetchEditsLo" +
      "g\0220.com.cczu.examples.hdfs.rpc.FetchEdit" +
      "sLogRequest\0321.com.cczu.examples.hdfs.rpc" +
      ".FetchEditsLogResponseB6\n\"com.cczu.examp" +
      "les.hdfs.rpc.serviceB\016NameNodeServerP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          NameNodeModel.getDescriptor(),
        });
    NameNodeModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
